[package]
name = "image_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"

